### ISSUE TITLE
Failed Building wheel for yarl

### ISSUE THREAD

**Issue by habeas81** [XanIves/DnD-Avrae-GUI#1]
Hello, first thank you for building and sharing! 

As I was installing, I got an error.  "ERROR: Could not build wheels for multidict which use PEP 517 and cannot be installed directly"

By chance do you know how we can fix it? 

Thanks!

**Comment by XanIves** [comment]
Never seen that issue, but it seems like an issue either with the version of Pip you have or the version of python you have installed. 

Do you have python 9 or something installed? If so, try running “python8 -m pip install -r requirements.txt”

**Comment by habeas81** [comment]
had to install and run python 3.8, I had 3.7 and 3.9 installed.. figures. 

ultimately this command worked 

py -3.8 -m pip install -r requirements.txt
